services:
  container1:
    container_name: container1
    image: shubh41/container1
    ports:
      - "6000:6000"
    depends_on:
      - container2

  container2:
    container_name: container2
    image: shubh41/container2
    ports:
      - "7000:7000"
      # Volumme attached to ":/usr/files"
    volumes:
      - .:/usr/files
